apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: httpproxies-exporter-clusterrole
rules:
- apiGroups: ["projectcontour.io"]
  resources: ["httpproxies"]
  verbs: ["get", "watch", "list"]
